# Spawner config file

# Valid entities
# You can make spawners any of the entity names listed at this link:
# http://jd.bukkit.org/rb/apidocs/src-html/org/bukkit/entity/EntityType.html#line.17
# Generally you would use the name that appears inside the quotes in the brackets.
# For example PigZombie will work while PIG_ZOMBIE will not.
valid_entities:
- Creeper
- Skeleton
- Spider
- Giant
- Zombie
- Slime
- Ghast
- PigZombie
- Enderman
- CaveSpider
- Silverfish
- Blaze
- LavaSlime
- EnderDragon
- WitherBoss
- Bat
- Witch
- Pig
- Sheep
- Cow
- Chicken
- Squid
- Wolf
- MushroomCow
- SnowMan
- Ozelot
- VillagerGolem
- EntityHorse
- Villager

# Preventing spawners being destroyed by explosions.
protect_from_explosions: true

# Default radius when removing entities with /spawner remove <entity>
remove_radius: 10

# Adds ability to limit the number of spawners a player can give/change.
limit:
    members: 0
    vip: 3
    elite: 6
    godlike: 10

# Allow baby spawners (not yet implemented)
allow_baby: false

# Allow mobs to wear armour (not yet implemented)
allow_armour: true